controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    simple_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    bumperbot_controller:
      type: diff_drive_controller/DiffDriveController

simple_velocity_controller:
  ros__parameters:
    joints:
      - wheel_left_joint
      - wheel_right_joint

bumperbot_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    use_stamped_vel: true # Use TwistStamped message
    left_wheel_names: ['wheel_left_joint']
    right_wheel_names: ['wheel_right_joint']
    publish_rate: 50.0 # Hz
    pose_covariance_diagonal: [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]

    wheel_radius: 0.033
    wheel_separation: 0.17
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    wheel_separation_multiplier: 1.0

    cmd_vel_timeout: 0.25 # Seconds; if no command received in this time stop robot
    base_frame_id: base_footprint
    publish_limited_velocity: true
    publish_wheel_data: true
    enable_odom_tf: true

    # Velocity limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0 # m/s
        min_velocity: -0.5 # m/s
        has_acceleration_limits: true
        max_acceleration: 0.8 # m/s^2
        min_acceleration: -0.4 # m/s^2
        has_jerk_limits: false

    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.7 # rad/s
        min_velocity: -1.7 # rad/s
        has_acceleration_limits: true
        max_acceleration: 1.5 # rad/s^2
        min_acceleration: -1.5 # rad/s^2
        has_jerk_limits: false
